---
title: "Linear Models"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
```


```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(stars = review_scores_location / 2) |> 
  select(
    price, stars, borough = neighbourhood_group,
    neighbourhood, room_type) |> 
  filter(borough != "Staten Island")
```

Let's fit a model

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```


Let's look at the fit

```{r}
fit
summary(fit)
summary(fit)$coef
coef(fit)
#fitted.values(fit)
```

Tidy up the output instead

```{r}
fit |> 
  broom::glance()
```

Tidy up the coefficients

```{r}
fit |> 
  broom::tidy() |> 
  mutate(term = str_replace(term, "^borough", "Borough: ")) |> 
  select(term, estimate, p.value) |> 
  knitr::kable(digits = 3)
```

## Fit another model

```{r}
fit = 
  nyc_airbnb |> 
  mutate(
    borough = fct_infreq(borough),
    room_type = fct_infreq(room_type)) |> 
  lm(price ~ stars + borough + room_type, data = _)

fit |> 
  broom::tidy()
```


## Quick look at diagnostics

```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = resid)) +
  geom_density() +
  xlim(-100, 500)

nyc_airbnb |> 
  modelr::add_predictions(fit)
```


## Different variables for plot
```{r}
nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = borough, y = resid)) + geom_violin()

nyc_airbnb |> 
  modelr::add_residuals(fit) |> 
  ggplot(aes(x = stars, y = resid)) + geom_point()
```


## Hypothesis Testing for categorical predictor

fitting a "null" and "alternative" model

```{r}
fit_null = lm(price ~ stars + borough, data = nyc_airbnb)
fit_alternative = lm(price ~ stars + borough + room_type, data = nyc_airbnb)


anova(fit_null, fit_alternative) |> 
  broom::tidy()
```


## Borough-level differences

```{r}

```


## Nesting Data

```{r}
nyc_airbnb |> 
  lm(price ~ stars * borough + room_type * borough, data = _) |> 
  broom::tidy() |> 
  knitr::kable(digits = 3)
```

Nesting within Boroughs

```{r}
nest_lm_res =
  nyc_airbnb |> 
  nest(data = -borough) |> 
  mutate(
    models = map(data, \(df) lm(price ~ stars + room_type, data = df)),
    results = map(models, broom::tidy)) |> 
  select(-data, -models) |> 
  unnest(results)
```

